# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactorkitCleverbot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactorkitCleverbot
  # Architecture
  pod 'ReactorKit'

  # Networking
  pod 'Alamofire'

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'RxKeyboard'
  pod 'RxViewController'
  pod 'RxCodable'

  # UI
  pod 'SnapKit'
  pod 'ManualLayout'

  # Misc
  pod 'Then'
  pod 'CGFloatLiteral'
  pod 'ReusableKit'
  pod 'UITextView+Placeholder'
  pod 'SwiftyColor'
  pod 'SwiftyImage'

end
